### ISSUE TITLE
Add new command which can add `alias dbt='dbtenv execute --'` to shell profile automatically

### ISSUE THREAD

**Issue by NiallRees** [brooklyn-data/dbtenv#19]
It would be useful to give users a command such as `dbtenv init` which automatically aliases dbt to itself in the user's shell profile, if it hasn't been already: https://github.com/brooklyn-data/dbtenv#running-dbt-with-dbtenv-more-seamlessly

Doing this in Windows is more complicated, so the initial version can skip that!

**Comment by danthelion** [comment]
I was also thinking about a script like this when setting up dbt/dbtenv. I was also thinking that we could include installing the autocompletions as well (https://github.com/dbt-labs/dbt-completion.bash/blob/master/README.md), which I think are pretty useful.
