### ISSUE TITLE
Support dbt 1.0.0

### ISSUE THREAD

**Issue by jaypeedevlin** [brooklyn-data/dbtenv#4]
Per [the release notes for 1.0.0rc1](https://github.com/dbt-labs/dbt-core/releases/tag/v1.0.0rc1):

> In v1.0.0, `pip install dbt` will raise an explicit error. Instead, please use `pip install dbt-<adapter>` (to use dbt with that database adapter), or `pip install dbt-core` (for core functionality). For parity with the previous behavior of `pip install dbt`, you can use: `pip install dbt-core dbt-postgres dbt-redshift dbt-snowflake dbt-bigquery` (https://github.com/dbt-labs/dbt-core/issues/4100, [#4133](https://github.com/dbt-labs/dbt-core/pull/4133))

In order to support >= 1.0.0 we need to add logic around this change.

**Comment by NiallRees** [comment]
You cool taking this on?

**Comment by jaypeedevlin** [comment]
Yep, I may need some support but thinking this will be the start of my contributions to the project.
